Repository astropy/photutils, pull requests merged in 2020-11, with the labels that each got.

#1111 Update psf.rst
  docs/psf.rst
Labels: docs, no-changelog-entry-needed, psf

#1112 Replace travis with GitHub actions for CI tests
  .github/workflows/ci_tests.yml
  .github/workflows/cron_tests.yml
  .travis.yml
Labels: infrastructure, no-changelog-entry-needed, testing

#1113 Update CI badge in README
  README.rst
Labels: docs, no-changelog-entry-needed

#1114 Remove name section from GitHub Actions workflow
  .github/workflows/ci_tests.yml
  .github/workflows/cron_tests.yml
Labels: no-changelog-entry-needed, testing

#1116 Fix coverage in actions workflow
  .github/workflows/ci_tests.yml
  tox.ini
Labels: no-changelog-entry-needed, testing

#1120 Drop support for python 3.6
  .github/workflows/ci_tests.yml
  CHANGES.rst
  docs/install.rst
  setup.cfg
  tox.ini
Labels: infrastructure

#1124 Update actions workflows
  .github/workflows/ci_tests.yml
  .github/workflows/cron_tests.yml
Labels: infrastructure, no-changelog-entry-needed, testing

#1125 Replace OrderedDict with dict
  docs/grouping.rst
  photutils/aperture/photometry.py
  photutils/datasets/make.py
  photutils/isophote/isophote.py
Labels: no-changelog-entry-needed, refactoring

#1126 Move linkcheck to weekly cron job
  .github/workflows/ci_tests.yml
  .github/workflows/cron_tests.yml
Labels: no-changelog-entry-needed, testing

#1127 DOC: Replace astropy channel with conda-forge channel
  docs/install.rst
Labels: docs, no-changelog-entry-needed
