Repository astropy/photutils, pull requests merged in 2022-10, with the labels that each got.

#1410 CI: minor fixes to tox config
  tox.ini
Labels: testing, no-changelog-entry-needed

#1419 Add xyorigin attribute to CutoutImage
  CHANGES.rst
  photutils/utils/cutouts.py
  photutils/utils/tests/test_cutouts.py
Labels: utils, enhancement

#1420 Add keywords to SourceCatalog make_cutouts
  CHANGES.rst
  photutils/segmentation/catalog.py
  photutils/segmentation/tests/test_catalog.py
Labels: enhancement, segmentation

#1421 Fix Kron photometry for custom minimum Kron or circular radius
  CHANGES.rst
  photutils/segmentation/catalog.py
  photutils/segmentation/tests/test_catalog.py
Labels: bug, segmentation

#1424 Pin sphinx to <5.2
  setup.cfg
Labels: docs

#1425 Use detection catalog centroids and shape parameters in SourceCatalog
  CHANGES.rst
  photutils/segmentation/catalog.py
  photutils/segmentation/tests/test_catalog.py
  photutils/segmentation/utils.py
Labels: API, enhancement, segmentation

#1428 Used SPDX license expression in project metadata
  setup.cfg
Labels: infrastructure, no-changelog-entry-needed

#1429 Update circle-ci 32-bit linux image
  .circleci/config.yml
Labels: testing

#1416 Update actions workflows and tox config
  .github/workflows/ci_tests.yml
  .github/workflows/cron_tests.yml
  .github/workflows/publish.yml
  tox.ini
Labels: testing

#1430 Add py311 to CI tests
  .github/workflows/ci_tests.yml
  .github/workflows/cron_tests.yml
Labels: testing, no-changelog-entry-needed

#1431 Add Python 3.11 to publish workflow
  .github/workflows/publish.yml
Labels: testing, releases, Build all wheels

#1432 Deprecate axes keywords in favor of ax
  CHANGES.rst
  docs/segmentation.rst
  photutils/aperture/bounding_box.py
  photutils/aperture/core.py
  photutils/background/background_2d.py
  photutils/segmentation/catalog.py
  photutils/segmentation/core.py
Labels: API, aperture, segmentation, background

#1433 Deprecate top level imports
  CHANGES.rst
  photutils/__init__.py
  photutils/segmentation/core.py
Labels: API, aperture, psf, detection, segmentation, background, psf_matching
