Repository astropy/photutils, pull requests merged in 2025-06, with the labels that each got.

#2053 Partial revert of limited API builds
  .github/workflows/ci_tests.yml
  pyproject.toml
Labels: no-changelog-entry-needed, installation

#2054 Update GitHub icon in docs header
  .readthedocs.yaml
  docs/conf.py
Labels: docs, no-changelog-entry-needed

#2056 Set persist-credentials to false in checkout actions
  .github/workflows/ci_cron_daily.yml
  .github/workflows/ci_cron_weekly.yml
  .github/workflows/ci_tests.yml
  .github/workflows/codeql.yml
  .pre-commit-config.yaml
Labels: testing, no-changelog-entry-needed
